<?php

namespace app\models;

use     app\components\Y;
use Yii;
use yii\base\Model;

use kartik\mpdf\Pdf;

use app\models\Pay;

/**
 * This is the model class for table "{{%user_payment}}".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $fioname
 * @property string $nvb1
 * @property string $dmbs2
 * @property string $bnk
 * @property string $ibnn
 * @property string $bic1
 */
class PaymentForm extends \yii\db\ActiveRecord
{

  /*public $fname;
    public $fioname;
    public $nvb1;
    public $dmbs2;
    public $bnk;
    public $ibnn;
    public $bic1;
  */




    public function rules()
    {
        return [
            [['fname', 'fioname', 'nvb1', 'dmbs2', 'bnk', 'ibnn', 'bic1'], 'required'],
//            [['fname', 'fioname', 'bnk'], 'string'],
//            [['nvb1'], 'integer'],
//            ['email','email'],
			//['user_id', 'unique', 'message' => 'Ошибка user_id'],
            [['service', 'additionals', 'test'], 'safe'],
        ];

    }
//    public function attributeLabels()  {
//        return [
//            'contact_value' => Yii::t('site', 'CONNECTION_TYPE'),
//            'message' => Yii::t('site', 'YOUR_MESSAGE'),
//            'verify_code' => Yii::t('site', 'VERIFY_CODE'),
//        ];
//    }




	public static function tableName() {
        return '{{%user_payment}}';
    }
	
	
	/**
     * @inheritdoc
     * @return PaymentFormQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new PaymentFormQuery(get_called_class());
    }
	
	
	
	 public function afterValidate()
    {
        parent::afterValidate(); // TODO: Change the autogenerated stub

        $this->user_id= Yii::$app->user->identity->id;

    }



    public function generatePdfContent($pay_id){
//        $pay_date = date("d-m-Y");
//        $expire_date = date("d-m-Y", strtotime("+1 months"));
        $pay = Pay::findOne($pay_id);
        $user = User::findOne($pay->user_id);
        $profile = UserProfile::findOne(['user_id' => $pay->user_id]);
        $contacts = UserContact::find()->where(['user_id' => $pay->user_id])->indexBy('id')->all();
        $pay_date = date("d/m/Y", $pay->date1_int);
        $expire_date = date("d/m/Y", $pay->date2_int);
        $html = null;
        $html .= '<!DOCTYPE html>
            <html lang="en">
              <head>
                <meta charset="utf-8">
                <title>Example 1</title>
                <link rel="stylesheet" href="style.css" media="all" />
              </head>
              <body>
                <header class="clearfix">
                  <h1>INVOICE 321</h1>
                  <div id="company" class="clearfix">
                    <div>Company Name</div>
                    <div>455 Foggy Heights,<br /> AZ 85004, US</div>
                    <div>(602) 519-0450</div>
                    <div><a href="mailto:company@example.com">company@example.com</a></div>
                  </div>
                  <div id="project">
                    <div><span>CLIENT</span> '.$this->fioname.'</div>
                    <div><span>ADDRESS</span> '.$profile->zip .' '. $profile->address.'</div>
                    <div><span>EMAIL</span> <a href="mailto:'.$user->email.'">'.$user->email.'</a></div>
                    <div><span>DATE </span>' .$pay_date.'</div>
                    <div><span>DUE DATE </span> '.$expire_date.'</div>
                  </div>
                </header>
                <main>
                  <table>
                    <thead>
                      <tr>
                        <th class="desc">DESCRIPTION</th>
                        <th>PRICE</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td class="desc">Firm name:'.$this->fname.' from '. $pay_date.' to '.$expire_date.'  Client Number:'.Y::getUserPaymentId($pay->user_id).'</td>
                        <td class="unit">€50.00</td>
                      </tr>
                      <tr>
                        <td class="grand total">TOTAL</td>
                        <td class="grand total">€50</td>
                      </tr>
                    </tbody>
                  </table>

                </main>
                <footer>
                  Invoice was created on a computer and is valid without the signature and seal.
                </footer>
              </body>
            </html>';

        return $html;
    }
    public function getPdfCss(){
        $css = null;
        $css .= '
             .clearfix:after {
                  content: "";
                  display: table;
                  clear: both;
                }
                
                a {
                  color: #5D6975;
                  text-decoration: underline;
                }
                
                body {
                  position: relative;
                  width: 21cm;  
                  height: 29.7cm; 
                  margin: 0 auto; 
                  color: #001028;
                  background: #FFFFFF; 
                  font-family: Arial, sans-serif; 
                  font-size: 12px; 
                  font-family: Arial;
                }
                
                header {
                  padding: 10px 0;
                  margin-bottom: 30px;
                }
                
                #logo {
                  text-align: center;
                  margin-bottom: 10px;
                }
                
                #logo img {
                  width: 90px;
                }
                
                h1 {
                  border-top: 1px solid  #5D6975;
                  border-bottom: 1px solid  #5D6975;
                  color: #5D6975;
                  font-size: 2.4em;
                  line-height: 1.4em;
                  font-weight: normal;
                  text-align: center;
                  margin: 0 0 20px 0;
                }
                
                #project {
                  float: left;
                }
                
                #project span {
                  color: #5D6975;
                  text-align: right;
                  width: 52px;
                  margin-right: 10px;
                  display: inline-block;
                  font-size: 0.8em;
                }
                
                #company {
                  float: right;
                  text-align: right;
                }
                
                #project div,
                #company div {
                  white-space: nowrap;        
                }
                
                table {
                  width: 100%;
                  border-collapse: collapse;
                  border-spacing: 0;
                  margin-bottom: 20px;
                }
                
                table tr:nth-child(2n-1) td {
                  background: #F5F5F5;
                }
                
                table th,
                table td {
                  text-align: center;
                }
                
                table th {
                  padding: 5px 20px;
                  color: #5D6975;
                  border-bottom: 1px solid #C1CED9;
                  white-space: nowrap;        
                  font-weight: normal;
                }
                
                table .service,
                table .desc {
                  text-align: left;
                }
                
                table td {
                  padding: 20px;
                  text-align: right;
                }
                
                table td.service,
                table td.desc {
                  vertical-align: top;
                }
                
                table td.unit,
                table td.qty,
                table td.total {
                  font-size: 1.2em;
                }
                
                table td.grand {
                  border-top: 1px solid #5D6975;;
                }
                
                #notices .notice {
                  color: #5D6975;
                  font-size: 1.2em;
                }
                
                footer {
                  color: #5D6975;
                  width: 100%;
                  height: 30px;
                  position: absolute;
                  bottom: 0;
                  border-top: 1px solid #C1CED9;
                  padding: 8px 0;
                  text-align: center;
               }\'
        ';
        return $css;
    }

    public function generatePdf($pay_id){
        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            'format' => Pdf::FORMAT_A4,
            'orientation' => Pdf::ORIENT_PORTRAIT,
            'destination' => Pdf::DEST_STRING,
            //html content input
            'content' => $this->generatePdfContent($pay_id),
//            'content' => 'just text',
            'cssInline' => $this->getPdfCss(),
            // set mPDF properties on the fly
            'options' => ['title' => 'Krajee Report Title'],
            // call mPDF methods on the fly
            'methods' => [
                'SetHeader'=>['Krajee Report Header'],
                'SetFooter'=>['{PAGENO}'],
            ]
        ]);
        return $pdf->render();
    }

    ////////////////////////////////////////////////////////////
    public function sendMessage($user_id, $pay_id) {
        $model = User::findOne($user_id);
        $profile = UserProfile::findOne(['user_id' => $user_id]);
        $contacts = UserContact::find()->where(['user_id' => $user_id])->indexBy('id')->all();
//        $text = Yii::t('site', 'MESSAGE_FIRST_LINE') .'<br />';
//        $text .= '<br />' .Yii::t('site', 'MESSAGE') .': <br />';
//        $text .= '<br />' .Yii::t('site', 'CONNECTION') .': <br />';
        $text = "<form action='https://www.paypal.com/cgi-bin/webscr' method='post' target='_top'>
<input type='hidden' name='cmd' value='_s-xclick'>
<input type='hidden' name='hosted_button_id' value='6DB5Q7L8J463A'>
<input type='image' src='https://www.paypalobjects.com/en_US/DE/i/btn/btn_buynowCC_LG.gif' border='0' name='submit' alt='PayPal - The safer, easier way to pay online!'>
<img alt='' border='0' src='https://www.paypalobjects.com/en_US/i/scr/pixel.gif' width='1' height='1'>
</form>
";

        $pdf = $this->generatePdf($pay_id);
        $res = Yii::$app->mailer->compose()
            ->setFrom(Yii::$app->params['adminEmail'])
            ->setTo($model->email, Yii::$app->params['adminEmail'])
            ->setSubject('Оплата бизнес аккаунта')
            ->setHtmlBody($text)
//            ->attach(Swift_Attachment::newInstance('dd', 'filename.pdf', 'application/pdf'))
            ->attachContent($pdf, ['fileName' => 'order.pdf', 'contentType' => 'application/pdf'])
            ->send();

        return $res ? ['result' => 'ok', 'message' => Yii::t('site', 'BID_SENT')] : ['result' => 'err', 'message' => Yii::t('site', 'SEND_EMAIL_ERR'.var_dump($res))];
    }
	
	
	
	    public function sendMessagePaySuccess($user_id, $pay_id) {
        $model = User::findOne($user_id);
        $profile = UserProfile::findOne(['user_id' => $user_id]);
        $contacts = UserContact::find()->where(['user_id' => $user_id])->indexBy('id')->all();
//        $text = Yii::t('site', 'MESSAGE_FIRST_LINE') .'<br />';
//        $text .= '<br />' .Yii::t('site', 'MESSAGE') .': <br />';
//        $text .= '<br />' .Yii::t('site', 'CONNECTION') .': <br />';
        $text = "Бизнес аккаунт оплачен";

        $pdf = $this->generatePdf($pay_id);
        $res = Yii::$app->mailer->compose()
            ->setFrom(Yii::$app->params['adminEmail'])
            ->setTo($model->email, Yii::$app->params['adminEmail'] )
            ->setSubject('Бизнес аккаунт оплачен')
            ->setHtmlBody($text)
//            ->attach(Swift_Attachment::newInstance('dd', 'filename.pdf', 'application/pdf'))
            ->attachContent($pdf, ['fileName' => 'order.pdf', 'contentType' => 'application/pdf'])
            ->send();

        return $res ? ['result' => 'ok', 'message' => Yii::t('site', 'BID_SENT')] : ['result' => 'err', 'message' => Yii::t('site', 'SEND_EMAIL_ERR'.var_dump($res))];
    }
}